name: MiaApp
options:
  bundleIdPrefix: com.sviluppo
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 11.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    majorVersion: 8.0.0
  HaishinKit:
    url: https://github.com/shogo4405/HaishinKit.swift
    exactVersion: 1.8.0
targets:
  MiaApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
        excludes:
          - ".github"
          - ".git"
          - "project.yml"
          - "Info.plist"
    dependencies:
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseDatabase
      - package: Firebase
        product: FirebaseAuth
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: HaishinKit
        product: HaishinKit
    info:
      path: Info.plist
