name: MiaApp
options:
  bundleIdPrefix: com.sviluppo
targets:
  MiaApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
        excludes:
          - ".github"
          - "project.yml"
    info:
      path: Info.plist
