default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight / App Store Connect"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_PRIVATE_KEY"],
      is_key_content_base64: false,
      in_house: false
    )

    kc_name = "ci_keychain"
    kc_password = "password123"
    kc_path = File.expand_path("~/Library/Keychains/#{kc_name}-db")

    delete_keychain(name: kc_name) if File.exist?(kc_path)

    create_keychain(
      name: kc_name,
      password: kc_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    sh("curl -fsSL https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer -o /tmp/AppleWWDRCAG3.cer")
    sh("curl -fsSL https://www.apple.com/certificateauthority/AppleWWDRCAG6.cer -o /tmp/AppleWWDRCAG6.cer")
    sh("security import /tmp/AppleWWDRCAG3.cer -k #{kc_path} -T /usr/bin/codesign -T /usr/bin/security || true")
    sh("security import /tmp/AppleWWDRCAG6.cer -k #{kc_path} -T /usr/bin/codesign -T /usr/bin/security || true")
    sh("security set-keychain-settings -lut 7200 #{kc_path}")

    get_certificates(
      api_key: api_key,
      keychain_path: kc_path,
      keychain_password: kc_password
    )

    produce(
      api_key: api_key,
      app_identifier: "com.sviluppo.MiaApp",
      app_name: "VolleyStream Pro",
      skip_itc: true
    )

    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.sviluppo.MiaApp",
      force: true
    )

    build_app(
      project: "MiaApp.xcodeproj",
      scheme: "MiaApp",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "VolleyStreamPro.ipa",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "./build/VolleyStreamPro.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
