name: Compila IPA
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Scarica codice
        uses: actions/checkout@v4

      - name: Installa XcodeGen
        run: brew install xcodegen

      - name: Genera progetto Xcode
        run: xcodegen generate

      - name: Compila Progetto
        run: |
          xcodebuild build \
            -project MiaApp.xcodeproj \
            -scheme MiaApp \
            -sdk iphoneos \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -derivedDataPath DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Crea pacchetto IPA
        run: |
          mkdir -p Payload
          cp -r DerivedData/Build/Products/Release-iphoneos/*.app Payload/
          zip -r AppPerIphone.ipa Payload

      - name: Salva il file
        uses: actions/upload-artifact@v4
        with:
          name: pacchetto-ipa
          path: AppPerIphone.ipa
